import { PlaceModel } from '../../../types/index.js';

export const SEED_PLACES: PlaceModel[] = [
  // --- PATNA ---
  {
    id: "patna-golghar",
    externalId: "ext-patna-golghar",
    name: "Golghar",
    category: "history",
    badge: "Historical Landmark",
    rating: 4.4,
    reviewCount: 2540,
    priceLevel: "₹",
    entryFee: 15,
    recommendedDuration: 45,
    openingHours: "Open Today (6:00 AM - 6:00 PM)",
    latitude: 25.6190,
    longitude: 85.1438,
    address: "Opposite Gandhi Maidan, Patna, Bihar 800001",
    phoneNumber: "+91 612 222 5555",
    website: "https://tourism.bihar.gov.in/golghar",
    photos: ["https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "Iconic beehive-shaped granary engineered in 1786 by Captain John Garstin. Ascend the twin spiral staircases hugging its 29-meter exterior for a panoramic view over the Ganges and city skyline.",
    highlights: ["Twin 145-step spiral staircases", "Stunning panoramic Ganga views", "Light & Sound show at sunset"],
    crowdToday: "Moderate (35% capacity)",
    crowdByHour: [10, 25, 40, 65, 80, 85, 70, 50, 20],
    recommendedTransit: "5 min Auto or 12 min Walk from Gandhi Maidan",
    localFoodTip: "Try traditional Bihari Litti Chokha with roasted brinjal dip right outside the southern gate."
  },
  {
    id: "patna-bihar-museum",
    externalId: "ext-patna-bihar-museum",
    name: "Bihar Museum",
    category: "culture",
    badge: "World Architecture",
    rating: 4.7,
    reviewCount: 3820,
    priceLevel: "₹₹",
    entryFee: 100,
    recommendedDuration: 90,
    openingHours: "Open Today (10:00 AM - 5:00 PM)",
    latitude: 25.6080,
    longitude: 85.1220,
    address: "Bailey Road, Patna, Bihar 800001",
    phoneNumber: "+91 612 255 6001",
    website: "https://biharmuseum.org",
    photos: ["https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "Designed by Pritzker Prize laureate Fumihiko Maki, this sprawling modern museum houses the 2,300-year-old Didarganj Yakshi, Mauryan bronzes, and experiential tribal arts galleries.",
    highlights: ["Didarganj Yakshi sculpture", "Contemporary corten-steel pavilion", "Children's discovery lab"],
    crowdToday: "Low Wait (<5 mins)",
    crowdByHour: [15, 30, 50, 55, 60, 45, 30, 15, 0],
    recommendedTransit: "Direct AC e-bus corridor on Bailey Road",
    localFoodTip: "The Museum Cafe offers artisanal Makhana kheer and authentic regional herbal coolers."
  },
  {
    id: "patna-patna-sahib",
    externalId: "ext-patna-sahib",
    name: "Takht Sri Patna Sahib",
    category: "spiritual",
    badge: "Sacred Spiritual Seat",
    rating: 4.8,
    reviewCount: 4910,
    priceLevel: "Free",
    entryFee: 0,
    recommendedDuration: 60,
    openingHours: "Open 24/7",
    latitude: 25.5902,
    longitude: 85.2285,
    address: "Patna City, Jhauganj, Patna, Bihar 800008",
    phoneNumber: "+91 612 264 1222",
    website: "https://takhatpatnasahib.in",
    photos: ["https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "One of the five Takhts of Sikhism, marking the birthplace of Guru Gobind Singh Ji in 1666. Admire the marble domes, golden canopies, sacred relics, and partake in 24/7 Guru Ka Langar.",
    highlights: ["Sacred Guru relics & weapons", "24/7 communal Langar", "White marble Sikh architecture"],
    crowdToday: "Serene Morning Flow",
    crowdByHour: [40, 55, 60, 60, 50, 65, 80, 75, 50],
    recommendedTransit: "20 min via Ashok Rajpath or Patna Saheb Rail link",
    localFoodTip: "Fresh Kada Prashad prepared with pure desi ghee is offered to every visitor."
  },
  {
    id: "patna-sabhyata-dwar",
    externalId: "ext-patna-sabhyata-dwar",
    name: "Sabhyata Dwar & Riverfront",
    category: "nature",
    badge: "Civilization Gateway",
    rating: 4.5,
    reviewCount: 1680,
    priceLevel: "Free",
    entryFee: 0,
    recommendedDuration: 45,
    openingHours: "Open 24/7 (Best at Sunset)",
    latitude: 25.6267,
    longitude: 85.1482,
    address: "Ganga Riverfront Promenade, Near Gyan Bhawan, Patna",
    photos: ["https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "A 32-meter sandstone arch inspired by Mauryan imperial architecture standing right on the banks of the sacred Ganges, offering serene waterfront gardens and sunset boat cruises.",
    highlights: ["Mauryan Ashokan lion capital motif", "Ganga Aarti view platform", "Riverfront breeze promenade"],
    crowdToday: "Optimal Sunset Pacing",
    crowdByHour: [5, 10, 15, 20, 30, 60, 85, 75, 30],
    recommendedTransit: "Adjacent to Gyan Bhawan; 8 min walk from Golghar",
    localFoodTip: "Roasted spiced sweet corn (Bhutta) and kulhad chai right along the promenade."
  },
  {
    id: "patna-kumhrar",
    externalId: "ext-patna-kumhrar",
    name: "Kumhrar Archaeological Site",
    category: "history",
    badge: "Mauryan Capital",
    rating: 4.2,
    reviewCount: 1120,
    priceLevel: "₹",
    entryFee: 25,
    recommendedDuration: 60,
    openingHours: "Open Today (9:00 AM - 5:00 PM)",
    latitude: 25.5997,
    longitude: 85.1834,
    address: "Kankarbagh Main Rd, Kumhrar, Patna 800026",
    photos: ["https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "The excavated remnants of ancient Pataliputra, featuring the iconic 80-pillared Mauryan assembly hall from the 3rd century BCE where Emperor Ashoka held court.",
    highlights: ["Mauryan 80-pillared hall foundations", "Arogya Vihar monastery site", "Lush botanical groves"],
    crowdToday: "Peaceful & Quiet",
    crowdByHour: [10, 20, 30, 35, 35, 25, 15, 5, 0],
    recommendedTransit: "15 min auto from Patna Junction",
    localFoodTip: "Kankarbagh sweet shops nearby serve fresh hot Gulab Jamun and Singharas."
  },
  {
    id: "patna-buddha-smriti",
    externalId: "ext-patna-buddha-smriti",
    name: "Buddha Smriti Park",
    category: "nature",
    badge: "Peace Garden & Stupa",
    rating: 4.4,
    reviewCount: 2200,
    priceLevel: "₹",
    entryFee: 20,
    recommendedDuration: 60,
    openingHours: "Open Today (9:00 AM - 7:00 PM)",
    latitude: 25.6062,
    longitude: 85.1378,
    address: "Frazer Road, Near Patna Junction, Patna 800001",
    photos: ["https://images.unsplash.com/photo-1545231027-637d2f6210f8?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "Inaugurated by the 14th Dalai Lama, this 22-acre sanctuary houses the monumental Karuna Stupa with Buddha relics, Bodhi trees from Bodh Gaya and Anuradhapura, and laser fountain shows.",
    highlights: ["Karuna Stupa relic chamber", "Sacred Bodhi tree sapling", "Evening musical fountain"],
    crowdToday: "Moderate Evening Flow",
    crowdByHour: [10, 20, 35, 45, 55, 70, 80, 60, 20],
    recommendedTransit: "2 min walk from Patna Junction station exit",
    localFoodTip: "Station road fruit juice stalls and roasted peanut carts."
  },
  {
    id: "patna-maurya-lok",
    externalId: "ext-patna-maurya-lok",
    name: "Maurya Lok Culinary & Cultural Trail",
    category: "food",
    badge: "Street Food Capital",
    rating: 4.5,
    reviewCount: 3100,
    priceLevel: "₹",
    entryFee: 0,
    recommendedDuration: 45,
    openingHours: "Open Today (11:00 AM - 10:30 PM)",
    latitude: 25.6120,
    longitude: 85.1320,
    address: "Dak Bungalow Road, Maurya Lok Complex, Patna",
    photos: ["https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "Patna's liveliest cultural plaza where food lovers gather for authentic Sattu parathas, crisp singharas, Bihari dry sweets (Khaja & Balushahi), and vibrant evening open-air discussions.",
    highlights: ["Sattu Sherbet & Litti hub", "Local Madhubani painting stalls", "Vibrant youth energy"],
    crowdToday: "High Evening Atmosphere",
    crowdByHour: [5, 10, 20, 30, 40, 60, 85, 95, 70],
    recommendedTransit: "5 min from Gandhi Maidan",
    localFoodTip: "Grab a chilled glass of roasted cumin spiced mint sattu sherbet."
  },

  // --- VARANASI ---
  {
    id: "vns-kashi-vishwanath",
    externalId: "ext-vns-kashi-vishwanath",
    name: "Kashi Vishwanath Temple & Corridor",
    category: "spiritual",
    badge: "Sacred Jyotirlinga",
    rating: 4.9,
    reviewCount: 8900,
    priceLevel: "Free",
    entryFee: 0,
    recommendedDuration: 75,
    openingHours: "Open Today (3:00 AM - 11:00 PM)",
    latitude: 25.3109,
    longitude: 83.0107,
    address: "Lahori Tola, Varanasi, Uttar Pradesh 221001",
    photos: ["https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "One of the twelve revered Jyotirlingas, newly connected to the sacred riverfront via the grand Kashi Vishwanath Dham Corridor spanning 500,000 square feet.",
    highlights: ["Golden spire plated with one tonne of gold", "Direct Ganga riverfront gateway", "Ancient Gyanvapi well"],
    crowdToday: "High Devotional Flow",
    crowdByHour: [60, 80, 85, 75, 70, 75, 90, 80, 50],
    recommendedTransit: "Direct e-rickshaw to Godowlia Chowk, then 3 min walk",
    localFoodTip: "Blue Lassi shop nearby and famous Malaiyo milk foam dessert in Chowk."
  },
  {
    id: "vns-dashashwamedh",
    externalId: "ext-vns-dashashwamedh",
    name: "Dashashwamedh Ghat",
    category: "culture",
    badge: "World Famous Ganga Aarti",
    rating: 4.9,
    reviewCount: 12400,
    priceLevel: "Free",
    entryFee: 0,
    recommendedDuration: 90,
    openingHours: "Open 24/7 (Aarti 6:45 PM)",
    latitude: 25.3078,
    longitude: 83.0101,
    address: "Dashashwamedh Ghat Rd, Ghats of Varanasi, Varanasi 221001",
    photos: ["https://images.unsplash.com/photo-1571536802807-30451e3955d8?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "The primary and grandest ghat on the Ganges where seven priests perform the synchronized Maha Aarti every evening with towering multi-tiered brass oil lamps, conch shells, and incense.",
    highlights: ["Grand evening Ganga Aarti spectacle", "Traditional wooden boat rides", "Vibrant spiritual ghat life"],
    crowdToday: "Extremely Busy at Sunset",
    crowdByHour: [20, 30, 40, 50, 60, 85, 98, 90, 40],
    recommendedTransit: "5 min walk from Godowlia Crossing",
    localFoodTip: "Crispy Tamatar Chaat and hot Gulab Jamuns at Kashi Chaat Bhandar."
  },
  {
    id: "vns-assi-ghat",
    externalId: "ext-vns-assi-ghat",
    name: "Assi Ghat & Subah-e-Banaras",
    category: "nature",
    badge: "Dawn Cultural Awakening",
    rating: 4.7,
    reviewCount: 5200,
    priceLevel: "Free",
    entryFee: 0,
    recommendedDuration: 60,
    openingHours: "Open 24/7 (Best at Sunrise)",
    latitude: 25.2899,
    longitude: 83.0064,
    address: "Assi Ghat, Shivala, Varanasi 221005",
    photos: ["https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "The southernmost major ghat where the sacred river Assi meets the Ganges. Celebrated for Subah-e-Banaras morning music concerts, yoga sessions at dawn, and bohemian artistic cafes.",
    highlights: ["Dawn Subah-e-Banaras concerts", "Ganga morning yoga", "Scenic riverboat departures"],
    crowdToday: "Pleasant Dawn Crowd",
    crowdByHour: [75, 80, 60, 40, 30, 45, 65, 80, 50],
    recommendedTransit: "10 min by auto from Lanka / BHU",
    localFoodTip: "Wood-fired apple pie and masala chai at Pizzeria Vaatika Cafe."
  },
  {
    id: "vns-sarnath",
    externalId: "ext-vns-sarnath",
    name: "Sarnath Deer Park & Dhamek Stupa",
    category: "history",
    badge: "Birthplace of Dharma",
    rating: 4.8,
    reviewCount: 4600,
    priceLevel: "₹",
    entryFee: 25,
    recommendedDuration: 90,
    openingHours: "Open Today (6:00 AM - 6:00 PM)",
    latitude: 25.3811,
    longitude: 83.0233,
    address: "Sarnath, Varanasi, Uttar Pradesh 221007",
    photos: ["https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "Where Gautama Buddha preached his first sermon after attaining enlightenment. Home to the massive 43.6m Dhamek Stupa and the original Ashoka Lion Capital (India's national emblem) in the adjacent museum.",
    highlights: ["Massive 5th-century Dhamek Stupa", "Original Ashoka Lion Pillar", "Peaceful deer park grounds"],
    crowdToday: "Tranquil & Meditative",
    crowdByHour: [15, 30, 45, 55, 60, 50, 40, 20, 5],
    recommendedTransit: "30 min cab or auto from Varanasi city center",
    localFoodTip: "Traditional Tibetan butter tea and steamed momos in Sarnath market."
  },

  // --- JAIPUR ---
  {
    id: "jpr-hawa-mahal",
    externalId: "ext-jpr-hawa-mahal",
    name: "Hawa Mahal (Palace of Winds)",
    category: "history",
    badge: "Rajput Architectural Icon",
    rating: 4.7,
    reviewCount: 14500,
    priceLevel: "₹",
    entryFee: 50,
    recommendedDuration: 50,
    openingHours: "Open Today (9:00 AM - 5:00 PM)",
    latitude: 26.9239,
    longitude: 75.8267,
    address: "Hawa Mahal Rd, Badi Choupad, J.D.A. Market, Jaipur 302002",
    photos: ["https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "Built in 1799 by Maharaja Sawai Pratap Singh, this five-story pink sandstone honeycomb facade boasts 953 jharokha latticed windows designed to circulate gentle desert breezes.",
    highlights: ["953 intricate jharokha windows", "Rooftop view of City Palace", "Intricate colored glass inlays"],
    crowdToday: "Busy Mid-Day",
    crowdByHour: [20, 40, 65, 80, 85, 80, 65, 40, 10],
    recommendedTransit: "Badi Choupad Metro Station (Pink Line) - 2 min walk",
    localFoodTip: "LMB (Laxmi Misthan Bhandar) Ghewar and Pyaaz Kachori 5 min away."
  },
  {
    id: "jpr-city-palace",
    externalId: "ext-jpr-city-palace",
    name: "City Palace & Chandra Mahal",
    category: "culture",
    badge: "Royal Residence & Museum",
    rating: 4.6,
    reviewCount: 11200,
    priceLevel: "₹₹₹",
    entryFee: 300,
    recommendedDuration: 90,
    openingHours: "Open Today (9:30 AM - 5:00 PM)",
    latitude: 26.9258,
    longitude: 75.8236,
    address: "Tulsi Marg, Gangori Bazaar, J.D.A. Market, Jaipur 302002",
    photos: ["https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "The royal seat of the Maharaja of Jaipur, featuring a fusion of Rajput, Mughal, and European architecture with grand courtyards, Peacock Gate, and giant silver vessels holding sacred Ganga water.",
    highlights: ["Four seasonal courtyard gates (Peacock Gate)", "World's largest silver urns (Gangajalis)", "Royal textile and arms gallery"],
    crowdToday: "Moderate Steady",
    crowdByHour: [25, 45, 60, 70, 75, 65, 50, 30, 5],
    recommendedTransit: "Adjacent to Jantar Mantar; 5 min walk from Hawa Mahal",
    localFoodTip: "Baradari fine dining inside the palace courtyard."
  },
  {
    id: "jpr-amber-fort",
    externalId: "ext-jpr-amber-fort",
    name: "Amber Palace & Sheesh Mahal",
    category: "history",
    badge: "UNESCO World Heritage Fort",
    rating: 4.8,
    reviewCount: 18900,
    priceLevel: "₹₹",
    entryFee: 100,
    recommendedDuration: 120,
    openingHours: "Open Today (8:00 AM - 5:30 PM)",
    latitude: 26.9855,
    longitude: 75.8513,
    address: "Devisinghpura, Amer, Jaipur, Rajasthan 302001",
    photos: ["https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "Opulent 16th-century hilltop fortress overlooking Maota Lake, famous for its mirror palace (Sheesh Mahal), Ganesh Pol gateway, and marble subterranean courtyards.",
    highlights: ["Shimmering Sheesh Mahal mirror hall", "Ganesh Pol painted gate", "Maota Lake garden reflection"],
    crowdToday: "High Morning & Afternoon Flow",
    crowdByHour: [35, 65, 85, 90, 85, 75, 60, 30, 10],
    recommendedTransit: "20 min cab or AC low-floor bus 29 from Jaipur city center",
    localFoodTip: "Spicy Dal Baati Churma at 1135 AD restaurant inside Amber Fort."
  },
  {
    id: "jpr-nahargarh",
    externalId: "ext-jpr-nahargarh",
    name: "Nahargarh Fort & Sunset Ramparts",
    category: "nature",
    badge: "Aravalli Ridge Bastion",
    rating: 4.7,
    reviewCount: 9800,
    priceLevel: "₹",
    entryFee: 50,
    recommendedDuration: 75,
    openingHours: "Open Today (10:00 AM - 5:30 PM)",
    latitude: 26.9372,
    longitude: 75.8155,
    address: "Krishna Nagar, Brahampuri, Jaipur, Rajasthan 302002",
    photos: ["https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "Perched along the rugged edge of the Aravalli Hills, offering the most breathtaking panoramic bird's-eye view of Jaipur city, particularly captivating at sunset from its stone ramparts.",
    highlights: ["Unrivaled panoramic city sunset", "Madhavendra Bhawan 12 queen suites", "Padao open-air rooftop lounge"],
    crowdToday: "Peak Flow at Golden Hour",
    crowdByHour: [10, 20, 30, 45, 60, 85, 95, 70, 20],
    recommendedTransit: "Scenic 25 min hill drive via winding mountain road",
    localFoodTip: "Cold beverage and masala peanuts with a 360-degree pink city view."
  },

  // --- DELHI ---
  {
    id: "del-qutub-minar",
    externalId: "ext-del-qutub-minar",
    name: "Qutub Minar & Mehrauli Complex",
    category: "history",
    badge: "UNESCO Monument",
    rating: 4.7,
    reviewCount: 16200,
    priceLevel: "₹",
    entryFee: 40,
    recommendedDuration: 75,
    openingHours: "Open Today (7:00 AM - 5:00 PM)",
    latitude: 28.5244,
    longitude: 77.1855,
    address: "Seth Sarai, Mehrauli, New Delhi 110030",
    photos: ["https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "A 72.5-meter fluted minaret founded in 1192 surrounded by the Quwwat-ul-Islam mosque and the rust-resistant 1,600-year-old Gupta Iron Pillar.",
    highlights: ["72.5m fluted red sandstone tower", "1600-year rustless Iron Pillar", "Alai Darwaza geometric carving"],
    crowdToday: "Moderate Steady",
    crowdByHour: [15, 30, 50, 65, 75, 70, 55, 35, 10],
    recommendedTransit: "Qutub Minar Metro Station (Yellow Line) + 5 min e-rickshaw",
    localFoodTip: "Chic design cafes and artisanal sourdough bakeries in Mehrauli."
  },
  {
    id: "del-humayun-tomb",
    externalId: "ext-del-humayun-tomb",
    name: "Humayun's Tomb",
    category: "culture",
    badge: "Precursor to Taj Mahal",
    rating: 4.8,
    reviewCount: 7900,
    priceLevel: "₹",
    entryFee: 40,
    recommendedDuration: 75,
    openingHours: "Open Today (6:00 AM - 6:00 PM)",
    latitude: 28.5933,
    longitude: 77.2507,
    address: "Mathura Road, Nizamuddin East, New Delhi 110013",
    photos: ["https://images.unsplash.com/photo-1566127444979-b3d2b654e3d7?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "The earliest grand Mughal garden tomb in India, featuring symmetrical Persian charbagh water channels, red sandstone jalis, and white marble dome.",
    highlights: ["Symmetrical Charbagh Persian gardens", "Double-domed white marble mausoleum", "Isa Khan Tomb complex"],
    crowdToday: "Peaceful Morning Light",
    crowdByHour: [20, 35, 45, 60, 70, 65, 50, 30, 10],
    recommendedTransit: "JLN Stadium Metro Station (Violet Line)",
    localFoodTip: "Sufi qawwali evening snacks at Nizamuddin Dargah lanes."
  },
  {
    id: "del-india-gate",
    externalId: "ext-del-india-gate",
    name: "India Gate & Kartavya Path",
    category: "nature",
    badge: "National War Memorial",
    rating: 4.8,
    reviewCount: 22000,
    priceLevel: "Free",
    entryFee: 0,
    recommendedDuration: 60,
    openingHours: "Open 24/7",
    latitude: 28.6129,
    longitude: 77.2295,
    address: "Rajpath, India Gate, New Delhi 110001",
    photos: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "A 42-meter triumphal arch memorializing 84,000 soldiers, fronted by the grand Kartavya Path lawns, Amar Jawan Jyoti, and the sunken National War Memorial.",
    highlights: ["42m triumphal memorial arch", "National War Memorial chakra rings", "Vibrant evening pedestrian lawns"],
    crowdToday: "High Evening Walkers",
    crowdByHour: [10, 20, 30, 40, 50, 70, 95, 90, 60],
    recommendedTransit: "Central Secretariat Metro Station",
    localFoodTip: "Ice creams and roasted spiced peanuts on the lawns."
  },

  // --- MUMBAI ---
  {
    id: "bom-gateway-india",
    externalId: "ext-bom-gateway-india",
    name: "Gateway of India",
    category: "history",
    badge: "Iconic Arabian Sea Arch",
    rating: 4.7,
    reviewCount: 28000,
    priceLevel: "Free",
    entryFee: 0,
    recommendedDuration: 60,
    openingHours: "Open 24/7",
    latitude: 18.9220,
    longitude: 72.8347,
    address: "Apollo Bandar, Colaba, Mumbai, Maharashtra 400001",
    photos: ["https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "A 26-meter basalt triumphal arch facing the Arabian Sea harbor, built in Indo-Saracenic style to commemorate the 1911 visit of King George V, flanked by the historic Taj Mahal Palace Hotel.",
    highlights: ["Basalt archway by the harbor", "Ferry departures to Elephanta Caves", "Historic Taj Mahal Hotel facade"],
    crowdToday: "Lively Harbor Promenade",
    crowdByHour: [20, 40, 60, 75, 85, 95, 90, 70, 30],
    recommendedTransit: "Churchgate or CSMT station + 10 min taxi",
    localFoodTip: "Bhel puri, sev puri, and Bun Maska at nearby Colaba cafes."
  },
  {
    id: "bom-marine-drive",
    externalId: "ext-bom-marine-drive",
    name: "Marine Drive (Queen's Necklace)",
    category: "nature",
    badge: "Coastal Sunset Promenade",
    rating: 4.8,
    reviewCount: 21500,
    priceLevel: "Free",
    entryFee: 0,
    recommendedDuration: 60,
    openingHours: "Open 24/7",
    latitude: 18.9432,
    longitude: 72.8230,
    address: "Netaji Subhash Chandra Bose Road, Mumbai 400020",
    photos: ["https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "A 3.6-kilometer curved boulevard hugging Back Bay, famous for its interlocking tetrapods, Art Deco buildings, and dazzling golden streetlamp curve known as the Queen's Necklace.",
    highlights: ["Sea-breeze tetrapod promenade", "World's second largest Art Deco collection", "Golden sunset over the Arabian Sea"],
    crowdToday: "Bustling Evening Gathering",
    crowdByHour: [15, 20, 25, 30, 50, 80, 95, 85, 50],
    recommendedTransit: "5 min walk from Marine Lines Station",
    localFoodTip: "Roasted corn on the cob (Bhutta) with lime and red chili."
  },

  // --- KOLKATA ---
  {
    id: "ccu-victoria-memorial",
    externalId: "ext-ccu-victoria-memorial",
    name: "Victoria Memorial Hall",
    category: "history",
    badge: "White Makrana Marble Palace",
    rating: 4.8,
    reviewCount: 24000,
    priceLevel: "₹",
    entryFee: 50,
    recommendedDuration: 90,
    openingHours: "Open Today (10:00 AM - 5:00 PM)",
    latitude: 22.5448,
    longitude: 88.3426,
    address: "1, Queens Way, Maidan, Kolkata, West Bengal 700071",
    photos: ["https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "Magnificent white Makrana marble monument commissioned in 1906, set amidst 64 acres of manicured gardens, reflecting pools, and housing 25 galleries of rare historical art.",
    highlights: ["Makrana white marble architecture", "Angel of Victory revolving bronze finial", "Sprawling lake garden grounds"],
    crowdToday: "Steady Afternoon Flow",
    crowdByHour: [15, 35, 55, 75, 80, 70, 50, 25, 5],
    recommendedTransit: "Rabindra Sadan or Maidan Metro Station",
    localFoodTip: "Kolkata Phuchka and spicy Jhalmuri outside the north gate."
  },
  {
    id: "ccu-howrah-bridge",
    externalId: "ext-ccu-howrah-bridge",
    name: "Howrah Bridge (Rabindra Setu)",
    category: "culture",
    badge: "Engineering Wonder",
    rating: 4.7,
    reviewCount: 19800,
    priceLevel: "Free",
    entryFee: 0,
    recommendedDuration: 45,
    openingHours: "Open 24/7",
    latitude: 22.5851,
    longitude: 88.3468,
    address: "Howrah Bridge, Kolkata, West Bengal 700001",
    photos: ["https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80"],
    source: "SEED",
    description: "An iconic balanced cantilever bridge constructed without nuts and bolts, spanning 705 meters across the Hooghly River, carrying over 100,000 vehicles and millions of pedestrians daily.",
    highlights: ["Historic riveted cantilever bridge", "Panoramic Hooghly River vista", "Adjacent vibrant flower market"],
    crowdToday: "High Daily Pulse",
    crowdByHour: [50, 70, 85, 90, 90, 85, 95, 80, 40],
    recommendedTransit: "Howrah Railway Station or Hooghly River Ferry",
    localFoodTip: "Clay cup Kulhad Chai and freshly fried Singara."
  }
];
